apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.overlay.csv: |
    p, christian, projects, get, workloads, allow
    p, christian, applications, workloads/*, *, allow
    g, christian, role:user
